// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUnsMfdMcDOK6wL16h0U6d5ZPR2MQ2e9M',
    appId: '1:13034273849:web:fe32ef1e2bdd643d4be1e8',
    messagingSenderId: '13034273849',
    projectId: 'test-project-420b5',
    authDomain: 'test-project-420b5.firebaseapp.com',
    databaseURL: 'https://test-project-420b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-project-420b5.appspot.com',
    measurementId: 'G-7LQRTQHGPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3kAZWgBZSb5PRy2LIigXP7OyDiA_nokA',
    appId: '1:13034273849:android:e989523b9c3f63124be1e8',
    messagingSenderId: '13034273849',
    projectId: 'test-project-420b5',
    databaseURL: 'https://test-project-420b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-project-420b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtVeg46W2Nzu0FN95wOyOgxLigg9NoJTA',
    appId: '1:13034273849:ios:7b44e2b5efc8b50a4be1e8',
    messagingSenderId: '13034273849',
    projectId: 'test-project-420b5',
    databaseURL: 'https://test-project-420b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-project-420b5.appspot.com',
    iosClientId: '13034273849-5rvposomju1eiacspnsn4jbkn28homh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.task1',
  );
}
